In [1]:
import numpy as np
import pandas as pd
import scipy
import matplotlib.pyplot as plt
import itertools
pd.options.mode.chained_assignment = None

In [5]:
tmap = np.array([
    [24, 70, 41, 21, 60],
    [47, 82, 87, 80, 35],
    [73, 89, 100, 90, 17],
    [77, 83, 85, 79, 55],
    [12, 27, 52, 15, 30]
    ]) * 7500

hunters = np.array([
    [2, 4, 3, 2, 4],
    [3, 5, 5, 5, 3],
    [4, 5, 8, 7, 2],
    [5, 5, 5 ,5, 4],
    [2, 3, 4, 2, 3]
])

In [7]:
fraction = np.ones((5, 5)) * 4

In [18]:
p1 = tmap / (hunters + fraction)
p1

array([[30000.        , 65625.        , 43928.57142857, 26250.        ,
        56250.        ],
       [50357.14285714, 68333.33333333, 72500.        , 66666.66666667,
        37500.        ],
       [68437.5       , 74166.66666667, 62500.        , 61363.63636364,
        21250.        ],
       [64166.66666667, 69166.66666667, 70833.33333333, 65833.33333333,
        51562.5       ],
       [15000.        , 28928.57142857, 48750.        , 18750.        ,
        32142.85714286]])

In [28]:
fraction2 = p1 / p1.sum() * 100

In [37]:
N = 1
res = np.zeros((5, 5))

for i in range(N):
    f1 = fraction2 * np.random.uniform(0.2, 3, (5, 5))
    f1 = f1 / f1.sum() * 100
    res += tmap / (hunters + f1)

In [43]:
f2 = (tmap / hunters - 10000) / (tmap / hunters - 10000).sum() * 100

In [44]:
f2

array([[3.48101758, 5.27591726, 4.02492657, 2.99149948, 4.46005377],
       [4.67761737, 4.91693733, 5.24328272, 4.78639917, 3.37223578],
       [5.52067631, 5.37382088, 3.64419027, 3.7607422 , 2.33880868],
       [4.59059193, 4.98220641, 5.11274456, 4.72113009, 4.05212202],
       [1.52294519, 2.50198138, 3.80736297, 2.01246329, 2.82832678]])

In [45]:
tmap / (hunters + f2)

array([[32840.61718524, 56598.17623171, 43772.69952018, 31553.64448097,
        53191.15129428],
       [45912.68138456, 62015.11411983, 63700.28218374, 61309.57768621,
        41194.3326009 ],
       [57506.41887811, 64344.66215761, 64409.80285389, 62728.01515793,
        29385.94653257],
       [60215.26140534, 62360.96256684, 63039.26653297, 60949.70385824,
        51228.73186322],
       [25546.80676495, 36804.92279274, 49952.84596215, 28037.63971836,
        38604.56156162]])